// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9A22_nz4iepAQLrSTe4hIpqev-9ogzI0',
    appId: '1:35844123331:web:3c521fcb8545dd50b85076',
    messagingSenderId: '35844123331',
    projectId: 'rentdone-92c6f',
    authDomain: 'rentdone-92c6f.firebaseapp.com',
    storageBucket: 'rentdone-92c6f.firebasestorage.app',
    measurementId: 'G-C45EW7JJ55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoBj8qlBknm-g4wsAHNz_tCyQAWfG3jx0',
    appId: '1:35844123331:android:3e3ff565505d29efb85076',
    messagingSenderId: '35844123331',
    projectId: 'rentdone-92c6f',
    storageBucket: 'rentdone-92c6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhTFlIqU5X370L0AsA0lYidHeSNwxgkZo',
    appId: '1:35844123331:ios:addaee0c2de20b92b85076',
    messagingSenderId: '35844123331',
    projectId: 'rentdone-92c6f',
    storageBucket: 'rentdone-92c6f.firebasestorage.app',
    iosBundleId: 'com.example.rentdone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhTFlIqU5X370L0AsA0lYidHeSNwxgkZo',
    appId: '1:35844123331:ios:addaee0c2de20b92b85076',
    messagingSenderId: '35844123331',
    projectId: 'rentdone-92c6f',
    storageBucket: 'rentdone-92c6f.firebasestorage.app',
    iosBundleId: 'com.example.rentdone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9A22_nz4iepAQLrSTe4hIpqev-9ogzI0',
    appId: '1:35844123331:web:96c9b87c3ea976e3b85076',
    messagingSenderId: '35844123331',
    projectId: 'rentdone-92c6f',
    authDomain: 'rentdone-92c6f.firebaseapp.com',
    storageBucket: 'rentdone-92c6f.firebasestorage.app',
    measurementId: 'G-PYS8KCYV1Y',
  );
}
